---
title: "Visualizacion"
author: "Lucía Martínez Valderas"
date: "2024-03-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Trabajo de Visualización
```{r}
#Primero cargamos las librerías que vamos a necesitar
library(readr)
library(ggplot2)
library(plotly)
library(scales)

#A continuación cargamos el fichero de datos
owid_covid_data <- read_csv("owid-covid-data.csv")

#Primero seleccionamos los paises que vamos a utilizar en la tabla, este será nuestro nuevo data frame con el que vamos a crear la gráfica:
paises_selecionados<-c("United States","Italy","France","Germany","Canada","Japan","United Kingdom","Spain")

#para acortar la funcion, crearemos un vector asignando a su pais cada color
pais_color <- c("Spain"="red",
                "United States" = "blue",
                "Italy" = "pink",
                "France" = "green",
                "Germany" = "purple",
                "Canada" = "orange",
                "Japan" = "black",
                "United Kingdom" = "cyan")

#asignaremos a una variable los elementos del data de la columna "location" los cuales coinciden con nuestro vector "paises_seleccionados
paises<-owid_covid_data[owid_covid_data$location %in% paises_selecionados, ]

#Después en la variable de casos totales sustituimos todos los NA que aparecen por 0
#paises$new_deaths_per_million[is.na(paises$new_deaths_per_million)]<-0
```


```{r}
#Ahora representamos la gráfica:
g<- ggplot(paises,aes(x=date,y=new_deaths_smoothed_per_million, group=location))+
  geom_line(aes(colour=location),size=ifelse(paises$location == "Spain",1.5,0.5))#Aquí hemos ensachado la línea de España
g
```


```{r}
#haremos un vector con las fechas que queremos poner de forma manual

fechas_manual <- as.Date(c("2020-08-08", "2020-11-16","2021-06-04","2021-09-12","2022-02-28","2022-12-31","2023-04-02","2023-11-18","2024-01-24"))

#Ponemos como queremos que sean las fehcas en el eje x
g<- g + scale_x_date(limits = c(min(fechas_manual), max(fechas_manual)),
                     breaks = fechas_manual,
                     labels = scales::date_format("%b %d, %Y"))
g
```


```{r}
#Ponemos los número que queremos en el eje y
g<- g + scale_y_continuous(breaks = seq(0, 20, by = 2)) 


#Ponemos manualmente los colores para poder reprsentar a España de rojo
g<- g + scale_color_manual(values= pais_color)

#Ponemos blanco el fondo de la gráfica
g<- g + theme_classic()
#ahora añadiremos las lineas discontinuas del grid
g <- g + theme(panel.grid.major.y = element_line(color = "grey",
                                          size = 0.5,
                                          linetype = 2))
g
```


```{r}
#Añadimos todos lo títulos e indicaciones a la gráfica

subtitulo <- "7-day rolling average. For some countries the number of confirmed deaths is much lower than the true number of deaths. This is because of limited
testing and challenges in the attribution of the cause of death."

#tambien aqui quitamos los titulos de los ejes x e y
g<- g + labs(title="Grupo-G",subtitle= subtitulo ,x=NULL,y=NULL,caption="Source: Johns Hopkins University CSSE COVID-19 Data")
g
```


```{r}
#podemos hacer que los nombres de las variables esten un poco inclinados
g <- g + theme(axis.text.x=element_text(angle=45, hjust=1))

#ahora haremos que el eje x sea de otro color en este caso gris continua y finita
g <- g + theme(axis.line.x = element_line(color = "grey",
                                   linewidth = 0.3,
                                   linetype = 1))
#y aqui eliminamos la linea del eje y
g <- g +  theme(axis.line.y = element_blank())
g
```


```{r}
#vamos a decorar un poco la leyenda
g <- g + theme(legend.background = element_rect(fill = "white", # Fondo
                                         colour = 1))        # Borde 
#mostramos la grafica que hemos estado creando
show(g)

#Creamos un gráfico interactivo con la librería plotly.
g_interactivo<-ggplotly(g)
g_interactivo

```

